# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.9.5

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      # run tests!
      - run: lein test

      # run uberjar
      - run: lein uberjar


  linux:
    docker:
      - image: circleci/clojure:lein-2.9.1
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      GRAALVM_HOME: /home/circleci/graalvm-ce-java11-21.0.0.2
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - linux-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Install lsof
          command: |
            sudo apt-get install lsof
      - run:
          name: Install native dev tools
          command: |
            sudo apt-get update
            sudo apt-get -y install gcc g++ zlib1g-dev
      - run:
          name: Download GraalVM
          command: |
            cd ~
            if ! [ -d graalvm-ce-java11-21.0.0.2 ]; then
              curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0.2/graalvm-ce-java11-linux-amd64-21.0.0.2.tar.gz
              tar xzf graalvm-ce-java11-linux-amd64-21.0.0.2.tar.gz
            fi
      - run:
          name: Build binary
          command: |
            scripts/compile
            VERSION=$(cat resources/VERSION)
            mkdir -p /tmp/release
            cp target/bingo-$VERSION-standalone.jar /tmp/release/bingo-$VERSION-standalone.jar
            cp target/bingo  /tmp/release/bingo
          no_output_timeout: 30m
      - save_cache:
          paths:
            - ~/.m2
            - ~/graalvm-ce-java11-21.0.0.2
          key: linux-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
      - store_artifacts:
          path: /tmp/release
          destination: release

workflows:
  build:
    jobs:
      - build
          filters:
            branches:
              only: lein-build
      - linux
          filters:
            branches:
              only: lein-build
