#!/usr/bin/env bash


if [ "$GRAALVM_HOME" != "" ]
then
    export JAVA_HOME=$GRAALVM_HOME
    export PATH=$GRAALVM_HOME/bin:$PATH
fi

java -version

set -eo pipefail

"$GRAALVM_HOME/bin/gu" install native-image

lein do clean, uberjar, native
