name: Test and Package 

on:
  push:
    branches: [ main ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Prepare Java
      uses: actions/setup-java@v2
      with:
        distribution: "temurin"
        java-version: "11"

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@3.7
      with:
        cli: 1.10.3.1075 # Clojure CLI based on tools.deps

    - name: Test and Package
      run: clojure -T:build ci  

    - name: Upload JAR Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: bingo-jvm
        path: target/bingo*
    
    - name: PreRelease
      uses: softprops/action-gh-release@v1 
      with:
        prerelease: true
        tag_name: latest
        files: target/bingo-0.1.0-SNAPSHOT.jar

  native:
    # if: startsWith(github.ref, 'refs/tags/') 

    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        gu-binary: [gu, gu.cmd]
        exclude:
          - os: ubuntu-latest
            gu-binary: gu.cmd
          - os: macos-latest
            gu-binary: gu.cmd
          - os: windows-latest
            gu-binary: gu

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: bingo-jvm
          path: target

      - name: Setup GraalVM
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '21.3.1'
          java: java11
          arch: amd64

      - name: Install native-image Component
        run: |
          ${{ matrix.gu-binary }} install native-image

      - name: Install MSVC Toolset (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        shell: bash
        run: |
          ./scripts/build-native.sh
          mv target/bingo target/bingo-native-linux

      - name: Build OSX
        if: ${{ matrix.os == 'macos-latest' }}
        shell: bash
        run: |
          ./scripts/build-native.sh
          mv target/bingo target/bingo-native-macos

      - name: Build Windows
        if: ${{ matrix.os == 'windows-latest' }}
        shell: powershell
        run: |
          scripts\build-native.bat
          mv target\bingo.exe target\bingo-native-windows.exe

      - name: Upload Native Image Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bingo-all
          path: target/bingo*


    
