name: Test and Package 

on:
  push:
    branches: [ main ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Prepare Java
      uses: actions/setup-java@v2
      with:
        distribution: "temurin"
        java-version: "11"

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@3.7
      with:
        cli: 1.10.3.1075 # Clojure CLI based on tools.deps

    - name: Test and Package
      run: clojure -T:build ci  

    - name: PreRelease
      uses: softprops/action-gh-release@v1 
      with:
        prerelease: true
        files: target/bingo-0.1.0-SNAPSHOT.jar
